///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubCategory {
/*
{
  "id": "3",
  "en_name": "Pharmacies",
  "ar_name": "صيدليات",
  "img": "https://hadayekhof.com/dalel/uploads/categories/Pharmacies.png"
}
*/

  String? id;
  String? enName;
  String? arName;
  String? img;

  SubCategory({
    this.id,
    this.enName,
    this.arName,
    this.img,
  });
  SubCategory.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    enName = json['en_name']?.toString();
    arName = json['ar_name']?.toString();
    img = json['img']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['en_name'] = enName;
    data['ar_name'] = arName;
    data['img'] = img;
    return data;
  }
}
