///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Advertisement {
/*
{
  "img": "https://hadayekhof.com/dalel/uploads/advertisement/اول_اعلان_للكبير_اغسطس1.jpg",
  "id": "14",
  "title_en": "اتفرج على الماتش معانا فى مطعم و كافيه الكبير اوى",
  "title_ar": "اتفرج على الماتش معانا فى مطعم و كافيه الكبير اوى",
  "body_en": "مطعم وكافيه الكبير اوي\r\nشارع الكابلات \r\n\r\nمستنينكوا تتفرجوا معانا علي الماتش و نشجع صلاح مع احلي المشروبات و\r\nالمشويات علي الفحم\r\nواحلي كريب وبيتزا \r\n\r\nومنسيناش الاطفال عملنا ليهم كيدز ايريا عشان نبسطهم و تتفرجو براحتكم",
  "body_ar": "مطعم وكافيه الكبير اوي\r\nشارع الكابلات \r\n\r\nمستنينكوا تتفرجوا معانا علي الماتش و نشجع صلاح مع احلي المشروبات و\r\nالمشويات علي الفحم\r\nواحلي كريب وبيتزا \r\n\r\nومنسيناش الاطفال عملنا ليهم كيدز ايريا عشان نبسطهم و تتفرجو براحتكم",
  "store_id": "183",
  "store_en_name": "الكبير اوى",
  "store_ar_name": "الكبير اوى",
  "is_notification": "0"
}
*/

  String? img;
  String? id;
  String? titleEn;
  String? titleAr;
  String? bodyEn;
  String? bodyAr;
  String? storeId;
  String? storeEnName;
  String? storeArName;
  String? isNotification;

  Advertisement({
    this.img,
    this.id,
    this.titleEn,
    this.titleAr,
    this.bodyEn,
    this.bodyAr,
    this.storeId,
    this.storeEnName,
    this.storeArName,
    this.isNotification,
  });
  Advertisement.fromJson(Map<String, dynamic> json) {
    img = json['img']?.toString();
    id = json['id']?.toString();
    titleEn = json['title_en']?.toString();
    titleAr = json['title_ar']?.toString();
    bodyEn = json['body_en']?.toString();
    bodyAr = json['body_ar']?.toString();
    storeId = json['store_id']?.toString();
    storeEnName = json['store_en_name']?.toString();
    storeArName = json['store_ar_name']?.toString();
    isNotification = json['is_notification']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['img'] = img;
    data['id'] = id;
    data['title_en'] = titleEn;
    data['title_ar'] = titleAr;
    data['body_en'] = bodyEn;
    data['body_ar'] = bodyAr;
    data['store_id'] = storeId;
    data['store_en_name'] = storeEnName;
    data['store_ar_name'] = storeArName;
    data['is_notification'] = isNotification;
    return data;
  }
}
