///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HomeAdvertisemen {
/*
{
  "img": "https://hadayekhof.com/dalel/uploads/advertisement/طارق_حاتم_عرض_اغسطس_1.jpeg",
  "id": "10",
  "title_en": "احمى نفسك من الانفلونزا وارفع مناعتك ضد الكورونا",
  "title_ar": "احمى نفسك من الانفلونزا وارفع مناعتك ضد الكورونا",
  "body_en": "متوفر بصيدليه طارق حاتم مصل الانفلونزا انفلوفاك\r\n\r\nاحمى نفسك من الانفلونزا وارفع مناعتك ضد الكورونا\r\n",
  "body_ar": "متوفر بصيدليه طارق حاتم مصل الانفلونزا انفلوفاك\r\n\r\nاحمى نفسك من الانفلونزا وارفع مناعتك ضد الكورونا\r\n",
  "store_id": "668",
  "store_en_name": "صيدلية طارق حاتم",
  "store_ar_name": "صيدلية طارق حاتم",
  "is_notification": "0"
}
*/

  String? img;
  String? id;
  String? titleEn;
  String? titleAr;
  String? bodyEn;
  String? bodyAr;
  String? storeId;
  String? storeEnName;
  String? storeArName;
  String? isNotification;

  HomeAdvertisemen({
    this.img,
    this.id,
    this.titleEn,
    this.titleAr,
    this.bodyEn,
    this.bodyAr,
    this.storeId,
    this.storeEnName,
    this.storeArName,
    this.isNotification,
  });
  HomeAdvertisemen.fromJson(Map<String, dynamic> json) {
    img = json['img']?.toString();
    id = json['id']?.toString();
    titleEn = json['title_en']?.toString();
    titleAr = json['title_ar']?.toString();
    bodyEn = json['body_en']?.toString();
    bodyAr = json['body_ar']?.toString();
    storeId = json['store_id']?.toString();
    storeEnName = json['store_en_name']?.toString();
    storeArName = json['store_ar_name']?.toString();
    isNotification = json['is_notification']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['img'] = img;
    data['id'] = id;
    data['title_en'] = titleEn;
    data['title_ar'] = titleAr;
    data['body_en'] = bodyEn;
    data['body_ar'] = bodyAr;
    data['store_id'] = storeId;
    data['store_en_name'] = storeEnName;
    data['store_ar_name'] = storeArName;
    data['is_notification'] = isNotification;
    return data;
  }
}
