/// Flutter icons NewIconsForApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NewIconsForApp
///      fonts:
///       - asset: fonts/NewIconsForApp.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class NewIconsForApp {
  NewIconsForApp._();

  static const _kFontFam = 'NewIconsForApp';
  static const String? _kFontPkg = null;

  static const IconData whatsapp = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_maps = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
