///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class News {
/*
{
  "img": "https://hadayekhof.com/dalel/uploads/news/عبارات-الف-مبروك-النجاحa_(1)1.png",
  "id": "19",
  "title": "تكريم اوائل الثانوية العامة فى منطقة وادى حوف",
  "start_date": "2022-08-20 21:16:00",
  "is_notification": "1"
}
*/

  String? img;
  String? id;
  String? title;
  String? startDate;
  String? isNotification;

  News({
    this.img,
    this.id,
    this.title,
    this.startDate,
    this.isNotification,
  });
  News.fromJson(Map<String, dynamic> json) {
    img = json['img']?.toString();
    id = json['id']?.toString();
    title = json['title']?.toString();
    startDate = json['start_date']?.toString();
    isNotification = json['is_notification']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['img'] = img;
    data['id'] = id;
    data['title'] = title;
    data['start_date'] = startDate;
    data['is_notification'] = isNotification;
    return data;
  }
}
