///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Store {
/*
{
  "id": "21",
  "en_name": "عيادة دكتور عبدالحميد جمال",
  "ar_name": "عيادة دكتور عبدالحميد جمال",
  "img": "https://hadayekhof.com/dalel/uploads/stores/primary.jpg",
  "rating": null
}
*/

  String? id;
  String? enName;
  String? arName;
  String? img;
  String? rating;

  Store({
    this.id,
    this.enName,
    this.arName,
    this.img,
    this.rating,
  });
  Store.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    enName = json['en_name']?.toString();
    arName = json['ar_name']?.toString();
    img = json['img']?.toString();
    rating = json['rating']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['en_name'] = enName;
    data['ar_name'] = arName;
    data['img'] = img;
    data['rating'] = rating;
    return data;
  }
}
