///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ZonesModel {
/*
{
  "id": "1",
  "en_name": "Wadi Hof",
  "ar_name": "وادى حوف",
  "img": "https://hadayekhof.com/dalel/uploads/zones/dsBuffer.bmp.png"
}
*/

  String? id;
  String? enName;
  String? arName;
  String? img;

  ZonesModel({
    this.id,
    this.enName,
    this.arName,
    this.img,
  });
  ZonesModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    enName = json['en_name']?.toString();
    arName = json['ar_name']?.toString();
    img = json['img']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['en_name'] = enName;
    data['ar_name'] = arName;
    data['img'] = img;
    return data;
  }
}
